name: "Mugridge Lab"
description: "Mugridge Lab website at UDel"
baseurl: ""
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "blog/page:num"
excerpt_separator: <!--more-->
exclude: [vendor]
permalink: pretty
highlighter: rouge
markdown: kramdown
kramdown: 
  parse_block_html: true
collections:
- sections
